apiVersion: v1
kind: Service
metadata:
  name: {{ include "hlf-ordnode.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7050
      protocol: TCP
      name: ord-port
{{- if .Values.channelParticipationEnabled }}
    - port: 7053
      targetPort: 7053
      protocol: TCP
      name: admin
{{- end }}
{{- if .Values.proxy.enabled }}
    - port: 7443
      targetPort: 7443
      protocol: TCP
      name: proxy
{{- end }}
    - port: {{ .Values.service.portOperations }}
      targetPort: 9444
      protocol: TCP
      name: ord-operations
  selector:
    app: {{ include "hlf-ordnode.name" . }}
    release: {{ .Release.Name }}
